/*

 BLOB_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char blob[] =
{
  0x18,0x18,0x24,0x24,0x42,0x42,0x99,0x99,
  0x99,0x99,0x42,0x42,0x24,0x24,0x18,0x18
};

/* End of BLOB_SPRITE.C */
